name: Test Composite Action

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use my composite action
        id: my-action
        uses: ./.github/actions/my-composite-action
        with:
          node-version: '18'

      - name: Display script result
        run: echo "Script Result: ${{ steps.my-action.outputs.script-result }}"
